### ISSUE TITLE
请问如果调用这个模型对一段没有标注的文本进行事件抽取，应该如何使用

### ISSUE THREAD

**Issue by lixuesi** [WuHuRestaurant/xf_event_extraction2020Top1#1]
请问如何调用这个模型对一个没有标注的文本进行事件抽取，并将抽取结果输出

**Comment by WuHuRestaurant** [comment]
目前没有支持纯文本进行事件抽取，可以参考 test.json 的数据格式，把需要抽取的文本转换成相同的 test.json 样式，训练好4个模型后可以抽取出相应的结果
