### ISSUE TITLE
test预测时，test.json 文件的由来

### ISSUE THREAD

**Issue by cypqyc** [WuHuRestaurant/xf_event_extraction2020Top1#10]
我理解 test.py 是预测 sentences.json的文件，当需要预测其它数据时，修改sentences.json 放入需要预测的新的数据集 ，除此之外是应该还需要处理test.json吗？那test.json在预测时是如何执行呢？

**Comment by WuHuRestaurant** [comment]
当时把sentences.json改了个名字。。

**Comment by cypqyc** [comment]
没太懂，test.json 和 sentences.json 是两个不同的文件吧我理解，test 处理的是test.json, 而且这个文件里已经有distant_triggers了

**Comment by WuHuRestaurant** [comment]
test.json 是我处理 sentences.json 后的文件，主要是加上distant_trigger 具体操作看代码

**Comment by cypqyc** [comment]
好的  也就是预测时 需要处理 sentences.json 为 test.json 格式 是吗？

**Comment by Biaocsu** [comment]
@cypqyc 你好，请问你知道test.json中distant_triggers信息怎样提取的吗？发现test.py代码也没法将sentences.json处理成test.json 文件啊。看了上面你和作者的对话，很迷
