### ISSUE TITLE
请问提取的事件，object可以为空吗？

### ISSUE THREAD

**Issue by llwowowowoll** [WuHuRestaurant/xf_event_extraction2020Top1#11]
我想自己构造训练集，提取的事件类型有"开幕"、"取消"、"降价"、"涨价"等等，这些事件都不需要object啊
请问一下，这种情况构造训练集时把role为object的，对应的text赋值为空，这样可以吗？
非常感谢啊~

**Comment by WuHuRestaurant** [comment]
可以 不过需要自己改代码 把 role1 提取器中的 object span分类器给取消了 解码那一块也需要有所改动
