### ISSUE TITLE
可以减少GPU的使用率吗

### ISSUE THREAD

**Issue by liuqingpu** [WuHuRestaurant/xf_event_extraction2020Top1#14]
你好，作者，我这边的显卡可能只有10G显存，配置中提到需要32G的GPU,想问问可以在哪设置参数，减少GPU的使用率？

**Comment by WuHuRestaurant** [comment]
batch size 开小一点就行 或者用小一点的 bert 模型

**Comment by liuqingpu** [comment]
谢谢作者。之前试过减小batchsize，改为2，貌似还是会内存溢出。可能我只有单卡10G左右。我会试试小的bert。



---原始邮件---
发件人: "WuHuRestaurant"<notifications@github.com&gt;
发送时间: 2021年1月17日(周日) 下午4:20
收件人: "WuHuRestaurant/xf_event_extraction2020Top1"<xf_event_extraction2020Top1@noreply.github.com&gt;;
抄送: "liuqingpu"<435665056@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [WuHuRestaurant/xf_event_extraction2020Top1] 可以减少GPU的使用率吗 (#14)




 
batch size 开小一点就行 或者用小一点的 bert 模型
