### ISSUE TITLE
data目录下有几个文件是什么数据？

### ISSUE THREAD

**Issue by ShaoboZhang** [WuHuRestaurant/xf_event_extraction2020Top1#15]
preliminary_data_pred_trigger、preliminary_data_pred_triggle_and_role、prelimiary_pred_triggers_pred_roles这几个是从原始数据生成的吧？请问这几个数据具体作用是什么？

**Comment by WuHuRestaurant** [comment]
主要是增强的数据（初赛过滤后的数据），因为这个比赛初赛和复赛的分布不一样，直接用初赛的数据会导致效果变差，这几个文件是初赛处理后的数据。

**Comment by ShaoboZhang** [comment]
好的，谢谢
