### ISSUE TITLE
马老师 这个项目能不能用cpu 跑啊

### ISSUE THREAD

**Issue by ztclear** [WuHuRestaurant/xf_event_extraction2020Top1#18]
麻烦告诉我一下 谢谢 具体要在哪设置

**Comment by WuHuRestaurant** [comment]
李在赣神魔 这项目你用CPU要训练到神魔时候了

**Comment by ztclear** [comment]
> 李在赣神魔 这项目你用CPU要训练到神魔时候了

就是 老师只提供了CPU的服务器  这波和服务器配合的并不是很好。所以马老师能告诉我方法嘛

**Comment by WuHuRestaurant** [comment]
这钵啊 这钵需要把 script/final/train.sh 里面的 export GPU_IDS="-1" . torch 里面 device=-1是在cpu 上跑。

**Comment by ztclear** [comment]
> 这钵啊 这钵需要把 script/final/train.sh 里面的 export GPU_IDS="-1" . torch 里面 device=-1是在cpu 上跑。

我之前也试了一下这里 不过搞成了GPU_IDS="1"。 终于调通了 芜湖 起飞，谢谢马老师 新年快乐嗷
