### ISSUE TITLE
马老师 教教我

### ISSUE THREAD

**Issue by ztclear** [WuHuRestaurant/xf_event_extraction2020Top1#25]
马老师 ，我阅读了TriggerExtractor的代码 ，然后对照了一下说明的PPT ，但是还是不特别清楚distant_trigger的意义是什么 。 我的暂时的理解是，之前训练集学习到的含有触发词的句子，会加入知识库，对之后的触发词提取造成影响，但是前面的触发词是通过trigger_dict进行识别的，含有触发词的句子加入知识库，trigger_dict中的触发词种类没有更新，这样做的作用是神魔？我有点混乱  。
然后请问“将训练集分成K份，用前K-1份的所有label当做后一份的知识库，构造训练数据的distant trigger” 这句话的代码实现在哪个py文件呢

**Comment by WuHuRestaurant** [comment]
distant trigger 就是一个远程监督库，后面那一句我不太了解你说的是啥
相关代码在 src_final/preprocess/convert_raw_data.py 中的 convert_raw_data 函数里面
