### ISSUE TITLE
train

### ISSUE THREAD

**Issue by strawberrybbq** [WuHuRestaurant/xf_event_extraction2020Top1#28]
train.sh模型找不到

**Comment by strawberrybbq** [comment]
运行时显示OSError: Model name './bert/torch_roberta_wwm' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased,...
是我模型没有下载对吗

**Comment by WuHuRestaurant** [comment]
这个文件夹里面你下的什么样子

**Comment by strawberrybbq** [comment]
&nbsp; &nbsp; &nbsp; 非常感谢您的回复！最近做的毕业设计需要学习事件抽取的部分，因此参考了您的算法进行学习。
&nbsp; &nbsp; &nbsp; 因为环境问题，我是使用google colab运行的 researchHub是项目的根目录，模型放在“/researchHub/BERT”文件夹下，在脚本中也改了相应BERT_dir。（如果在windows下运行可以使用train.py进行训练吗？）
&nbsp; &nbsp; &nbsp; 并且在readme的“并将 vocab.txt 中的两个 unused 改成 [INV] 和 [BLANK]（详见 processor 代码中的 fine_grade_tokenize）”这个部分，我发现vocab.txt里的内容是从[unused1]-[unused99],对此处如何改变存在一些疑问，如图：
&nbsp; &nbsp; &nbsp; 真的很感谢！








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WuHuRestaurant/xf_event_extraction2020Top1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WuHuRestaurant/xf_event_extraction2020Top1] train (#28)





 
这个文件夹里面你下的什么样子

**Comment by strawberrybbq** [comment]
再次附上我的运行截图和train.bash修改的路径部分，感谢！








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "顾盼"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 中午12:11
***@***.***&gt;;

主题:&nbsp;回复： [WuHuRestaurant/xf_event_extraction2020Top1] train (#28)



&nbsp; &nbsp; &nbsp; 非常感谢您的回复！最近做的毕业设计需要学习事件抽取的部分，因此参考了您的算法进行学习。
&nbsp; &nbsp; &nbsp; 因为环境问题，我是使用google colab运行的 researchHub是项目的根目录，模型放在“/researchHub/BERT”文件夹下，在脚本中也改了相应BERT_dir。（如果在windows下运行可以使用train.py进行训练吗？）
&nbsp; &nbsp; &nbsp; 并且在readme的“并将 vocab.txt 中的两个 unused 改成 [INV] 和 [BLANK]（详见 processor 代码中的 fine_grade_tokenize）”这个部分，我发现vocab.txt里的内容是从[unused1]-[unused99],对此处如何改变存在一些疑问，如图：
&nbsp; &nbsp; &nbsp; 真的很感谢！








------------------ 原始邮件 ------------------
发件人:                                                                                                                        "WuHuRestaurant/xf_event_extraction2020Top1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WuHuRestaurant/xf_event_extraction2020Top1] train (#28)





 
这个文件夹里面你下的什么样子

**Comment by strawberrybbq** [comment]
[
![image](https://user-images.githubusercontent.com/53890711/114506419-5617e000-9c64-11eb-80f4-e3bea9ec121f.png)
](url)

**Comment by strawberrybbq** [comment]
非常感谢您的回复！
因为环境问题，我是使用google colab运行的 researchHub是项目的根目录，模型放在“/researchHub/BERT”文件夹下，在脚本中也改了相应BERT_dir。
 并且在readme的“并将 vocab.txt 中的两个 unused 改成 [INV] 和 [BLANK]（详见 processor 代码中的 fine_grade_tokenize）”这个部分，我发现vocab.txt里的内容是从[unused1]-[unused99],对此处如何改变存在一些疑问，如图：
![image](https://user-images.githubusercontent.com/53890711/114506630-a8590100-9c64-11eb-8b27-62b475c2120f.png)
![image](https://user-images.githubusercontent.com/53890711/114506675-b870e080-9c64-11eb-9ccc-0b010a5fcb14.png)
![image](https://user-images.githubusercontent.com/53890711/114506734-c888c000-9c64-11eb-8dfa-8ee89a168227.png)

**Comment by strawberrybbq** [comment]
或者是出现此问题，是模型解析有误吗？
![image](https://user-images.githubusercontent.com/53890711/114728377-9dd85d80-9d71-11eb-9775-ba4a70579af2.png)

**Comment by WuHuRestaurant** [comment]
把bert_config.json 改成config.json

**Comment by strawberrybbq** [comment]
感谢你的回复 问题已解决 config.json文件名已改，除此之外，对tokenizer = BertTokenizer.from_pretrained(model_name)和bert_model = BertModel.from_pretrained(MODEL_PATH)这两个函数的参数也进行了修改。

**Comment by strawberrybbq** [comment]
谢谢作者！！
