### ISSUE TITLE
训练出来的模型中，没有test.sh中指定的模型名称

### ISSUE THREAD

**Issue by lixuesi** [WuHuRestaurant/xf_event_extraction2020Top1#3]
作者发布的test.sh中指定的模型名称是：
--trigger_ckpt_dir='./out/final/trigger/roberta_wwm_distant_trigger_pgd_enhanced/checkpoint-100000' \
--role1_ckpt_dir='./out/final/role1/roberta_wwm_distance_pgd_enhanced/checkpoint-884' \
--role2_ckpt_dir='./out/final/role2/roberta_wwm_pgd_enhanced/checkpoint-1056' \
--attribution_ckpt_dir='./out/final/attribution/roberta_wwm_pgd/checkpoint-100000' \
--trigger_start_threshold=0.5 \

但是在我本地训练出来的文件夹中，没有role1模型的884和role2模型的1056，如下图，请问这种情况下应该怎么指定？
![image](https://user-images.githubusercontent.com/73978062/99021575-eb228a00-259b-11eb-8ebd-6fea9e3d4af3.png)

**Comment by WuHuRestaurant** [comment]
readme 写的很清楚，你只跑一次 train.sh 跑得就是一个 task 的，4个任务需要训练四次

**Comment by lixuesi** [comment]
> readme 写的很清楚，你只跑一次 train.sh 跑得就是一个 task 的，4个任务需要训练四次

跑过四次了，就是每个任务对应的输出文件夹下面并没有test.sh指定的模型，比如role2这个输出文件夹中，没有checkpoint-1056

**Comment by WuHuRestaurant** [comment]
根据 eval 自己选一个线下最优的测试模型 保存的 checkpoint 是按照每一个 epoch 存的

**Comment by lixuesi** [comment]
> 根据 eval 自己选一个线下最优的测试模型 保存的 checkpoint 是按照每一个 epoch 存的

okkk好的，多谢您
