### ISSUE TITLE
运行test.sh的时候出现了TypeError: unsupported operand type(s) for /=: 'NoneType' and 'float'的问题，请问如何处理？

### ISSUE THREAD

**Issue by lixuesi** [WuHuRestaurant/xf_event_extraction2020Top1#4]
不好意思，还想问一个新的问题，运行test.sh的时候，出现了下面的问题
![image](https://user-images.githubusercontent.com/73978062/99069579-94dc3800-25e9-11eb-9a95-ded58a7cb258.png)
请问这种为什么会导致这种情况？以及我应该怎么处理呢？

**Comment by WuHuRestaurant** [comment]
我不是你的debugger 有问题请自行解决

**Comment by lixuesi** [comment]
> 我不是你的debugger有问题请自行解决

哦哦好的
