### ISSUE TITLE
The parameters "use_distant_trigger" different "use_trigger_distance"?

### ISSUE THREAD

**Issue by NoLoPhe** [WuHuRestaurant/xf_event_extraction2020Top1#5]
Please explain me the difference between the two above parameters. Thankyou.

**Comment by WuHuRestaurant** [comment]
1.The parameter **‘use_distant_trigger’** is used for the **trigger extraction task**. We use all the triggers in the supervision data and use some rules to construct a remote supervision library of triggers. Similar to the remote supervision method, if the text matches the knowledge base, the distant trigger label is set to 1, and then embedding is used as a feature of the model。

**Comment by WuHuRestaurant** [comment]
2. The parameter ‘use_trigger_distance’ is used for the role extraction task, used to characterize the relative distance between other words in the text and the trigger.

**Comment by NoLoPhe** [comment]
Thanks for your immediate reply!
