### ISSUE TITLE
bert模型获取

### ISSUE THREAD

**Issue by ZhaoZiheng1** [WuHuRestaurant/xf_event_extraction2020Top1#6]
RoBERTa-wwm-ext 这个模型的torch版本不能获取了，不知道在哪里下载，请问该怎么办

**Comment by WuHuRestaurant** [comment]
google 云还能下载，如果不能下载就下tf版本，用transformers里面的转换脚本转换过来

**Comment by llwowowowoll** [comment]
> RoBERTa-wwm-ext 这个模型的torch版本不能获取了，不知道在哪里下载，请问该怎么办

我这里有啊

**Comment by lwwlife** [comment]
您好！RoBERTa-wwm-ext这个模型的torch版本哪里能下载呀，求分享
