### ISSUE TITLE
请问bert目录下具体的文件

### ISSUE THREAD

**Issue by cypqyc** [WuHuRestaurant/xf_event_extraction2020Top1#9]
可以帮忙发下bert目录下具体的文件吗？我模型下载了，也放目录了，vocab.txt也改了，但是关于bert模型总是报错
以下是我的bert目录，可以帮忙看下是否有问题吗？
xf_event_extraction2020Top1-master
    bert
         torch_roberta_wwm
               bert_config.json
               pytorch_model.bin
               vocab.txt

**Comment by WuHuRestaurant** [comment]
transformers 版本问题，代码那样写要把 bert_config.json 重命名成 config.json

**Comment by cypqyc** [comment]
把我目录的文件名改成config.json是吗？

**Comment by cypqyc** [comment]
改完了，不报这个问题的错了，谢谢
